### ISSUE TITLE
Blind does not respond to short tap

### ISSUE THREAD

**Issue by Sinclair81** [Sinclair81/Homebridge-Logo-Platform#42]
from Nik's email:
When I just tap on the blind in Apple Home app to open (or close) the blind it doesn’t do it.
Instead I need to longtap the accessory and then slowly swipe it the required percentage ( so 0% or 100% to open or close it entirely).

**Comment by Sinclair81** [comment]
The short taps work in Homebridge v2.0.
But I still need to improve the blind UDF.
The correct values ​​are not returned to the Homebridge for all states.

I have now tested it again with my "real" Homebridge v1.8.5 and the kitchen blinds. It now works with short taps in the overview.

**Comment by NikVandewouwer** [comment]
Let me know when an update of the plugin is available so I can test as well!

**Comment by Sinclair81** [comment]
v1.4.5 is on the way.
It may not have always worked because in some cases an incorrect state was returned.

**Comment by NikVandewouwer** [comment]
> v1.4.5 is on the way. It may not have always worked because in some cases an incorrect state was returned.

Just updated and at first glance it seems to work much more reliably now! Thank you very much!!

I keep monitoring next few days.

**Comment by NikVandewouwer** [comment]
It’s much better but still does not always respond to short taps. Maybe we can reopen the ticket @Sinclair81 ?

**Comment by Dimi-user** [comment]
I made a custom UDF block for blinds with working taps if you want it.
I tailored this one specific to my needs but has some limitations due to the block limitation in the logo. You can fit 10 blinds in one logo and have a few spare blocks to do some other logic.

Behaviour in Homekit:
It will respond to taps. It will stop if you tap again while it's running. 
Setpoint value: If you set a value, it will go there. If you change the value while moving, the blinds will stop. After this, you can select another value and it will go there.

2 physical buttons response: 
Push the up or down button to go up or down automatically. Press either button to stop moving. If you long press the button (>0,5s) it will overwrite the program and keep on going until you release the button. The position will still follow within its limits. This can come handy if your blinds are not in the initial position and don’t have an iDevice with you..
When pressing a button, is will overwrite a command coming from homekit.

Limitations:
Only 1 runtime can be set, but there is a possibility to extend the closing time to be sure of the initial position.
You need to set the same time in 2 parameters in seconds x100.
In VM mapping it is required to map the PosR parameter to the same adres as the requested position adres, so Set and GetTargetPosition will have the same adres in the Homebridge. This is needed for the overwrite coming from the buttons to be possible.

I’ve added the position status as well, but I feel like it’s not necessary.
I used a custom block for months without position status and it works exactly te same on homekit. The only difference I can see, is that the feedback on Homebridge itself is now correct. For Homebridge I used a dummy VM containing 0 for all blinds.

I do think the values in the MUX of the position status should be 2-0-1-3 instead of 0-2-1-3 in the provided UDF.
2 = Stopped
1 = Opening
0 = Closing
3 = Error?
[Rollen V4.10 UDF.lma.zip](https://github.com/user-attachments/files/18163139/Rollen.V4.10.UDF.lma.zip)

**Comment by NikVandewouwer** [comment]
@Sinclair81 can we reopen this issue, single tap still doesn’t work most of the time :(

Or can we expect this to improve when Homebridge 2.0 comes?
